services:
  app:
    image: awesome-epic:llm
    env_file:
      - .env
    volumes:
      - ./volumes/.cache/:/app/tmp/.cache
    command: uv run xvfb-run --server-args='-screen 0 1920x1080x24' epic collect
